project:
  type: website

website:
  title: "universe-report"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Viz        
      - href: new_analysis.qmd
        text: TopPerf
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



